import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import SmallDevicesSideBar from "@/components/SmallDevicesSideBar";
import WholeContextProvider, { useWholeContext } from "@/context/WholeContext";
import ContextWrapper from "@/context/ContextWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[var(--BACKGROUNDCOLOR)] text-[var(--PARATEXT)] w-full h-full`}
      >
        <ContextWrapper children={children} />
      </body>
    </html>
  );
}
